/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.java_desktop;

import java.text.DecimalFormat;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author khoan
 */
public class Bai1 extends javax.swing.JPanel {

    
//    // Phương thức để tính toán và trả về kết quả dưới dạng chuỗi
//    public String Output() {
//        StringBuilder result = new StringBuilder();
//        for (int i = 0; i < 10; i++) {
//            result.append(i).append(", ");
//        }
//        return result.toString();
//    }
    /**
     * Creates new form Bai1
     */
    public Bai1() {
        initComponents();
        ButtonGroup bg = new ButtonGroup();
        bg.add(RDSum);
        bg.add(RDMinus);
        bg.add(RDTime);
        bg.add(RDDivide);
//        txtSum.setText(Output());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Caculate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        SoA = new javax.swing.JTextField();
        SoB = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSum = new javax.swing.JTextField();
        txtMinus = new javax.swing.JTextField();
        txtTime = new javax.swing.JTextField();
        txtDivide = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        RDSum = new javax.swing.JRadioButton();
        RDMinus = new javax.swing.JRadioButton();
        RDTime = new javax.swing.JRadioButton();
        RDDivide = new javax.swing.JRadioButton();
        txtTotal = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(900, 700));

        Caculate.setText("Tính");
        Caculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaculateActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Bài 1");

        SoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoAActionPerformed(evt);
            }
        });

        SoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoBActionPerformed(evt);
            }
        });

        jLabel2.setText("Nhập số A");

        jLabel3.setText("Nhập số B");

        jLabel4.setText("Tính bằng button:");

        txtMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinusActionPerformed(evt);
            }
        });

        jLabel5.setText("Tổng");

        jLabel6.setText("Hiệu");

        jLabel7.setText("Tích");

        jLabel8.setText("Thương");

        jLabel9.setText("Tính bằng Radio Button:");

        RDSum.setText("Tổng");
        RDSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RDSumActionPerformed(evt);
            }
        });

        RDMinus.setText("Hiệu");
        RDMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RDMinusActionPerformed(evt);
            }
        });

        RDTime.setText("Tích");
        RDTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RDTimeActionPerformed(evt);
            }
        });

        RDDivide.setText("Thương");
        RDDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RDDivideActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(SoA, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtSum, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel9)
                                            .addComponent(RDSum)
                                            .addComponent(RDMinus)
                                            .addComponent(RDTime)
                                            .addComponent(RDDivide))
                                        .addGap(136, 136, 136)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtTotal, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtMinus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(111, 111, 111)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(SoB, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(99, 99, 99))
            .addGroup(layout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(Caculate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(Caculate)
                .addGap(41, 41, 41)
                .addComponent(jLabel4)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMinus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDivide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jLabel9)
                .addGap(40, 40, 40)
                .addComponent(RDSum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RDMinus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RDTime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addComponent(RDDivide)
                .addContainerGap(96, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SoAActionPerformed

    private void SoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SoBActionPerformed

    private void txtMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinusActionPerformed

    private void CaculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaculateActionPerformed
        if(SoA.getText().equals("") || SoB.getText().equals("")){
            JOptionPane.showMessageDialog(this, "vui long nhap du thong tin", "Thiếu thông tin", JOptionPane.WARNING_MESSAGE);
        }
        else{          
            int a = Integer.parseInt(SoA.getText());
            int b = Integer.parseInt(SoB.getText());

            int s = a+b;
            int m = a-b;
            int t = a*b;
            float d = (float)a/b;
            DecimalFormat decimalFormat = new DecimalFormat("#.####"); // Xác định số lượng chữ số thập phân

            txtSum.setText(Integer.toString(s));
            txtMinus.setText(Integer.toString(m));
            txtTime.setText(Integer.toString(t));
            txtDivide.setText(decimalFormat.format(d));
        }

        
    }//GEN-LAST:event_CaculateActionPerformed

    private void RDSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RDSumActionPerformed
        if(SoA.getText().equals("") || SoB.getText().equals("")){
            JOptionPane.showMessageDialog(this, "vui long nhap du thong tin", "Thiếu thông tin", JOptionPane.WARNING_MESSAGE);
        }
        else{ 
            int a = Integer.parseInt(SoA.getText());
            int b = Integer.parseInt(SoB.getText());

            int s = a+b;
            txtTotal.setText(Integer.toString(s));
        }
    }//GEN-LAST:event_RDSumActionPerformed

    private void RDMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RDMinusActionPerformed
        if(SoA.getText().equals("") || SoB.getText().equals("")){
            JOptionPane.showMessageDialog(this, "vui long nhap du thong tin", "Thiếu thông tin", JOptionPane.WARNING_MESSAGE);
        }
        else{ 
            int a = Integer.parseInt(SoA.getText());
            int b = Integer.parseInt(SoB.getText());

            int m = a-b;
            txtTotal.setText(Integer.toString(m));
        }
    }//GEN-LAST:event_RDMinusActionPerformed

    private void RDTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RDTimeActionPerformed
        if(SoA.getText().equals("") || SoB.getText().equals("")){
            JOptionPane.showMessageDialog(this, "vui long nhap du thong tin", "Thiếu thông tin", JOptionPane.WARNING_MESSAGE);
        }
        else{ 
            int a = Integer.parseInt(SoA.getText());
            int b = Integer.parseInt(SoB.getText());

            int t = a*b;
            txtTotal.setText(Integer.toString(t));
        }
    }//GEN-LAST:event_RDTimeActionPerformed

    private void RDDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RDDivideActionPerformed
        if(SoA.getText().equals("") || SoB.getText().equals("")){
            JOptionPane.showMessageDialog(this, "vui long nhap du thong tin", "Thiếu thông tin", JOptionPane.WARNING_MESSAGE);
        }
        else{ 
            int a = Integer.parseInt(SoA.getText());
            int b = Integer.parseInt(SoB.getText());

            float d = (float)a/b;
            DecimalFormat decimal = new DecimalFormat("#.####");
            txtTotal.setText(decimal.format(d));
        }
    }//GEN-LAST:event_RDDivideActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Caculate;
    private javax.swing.JRadioButton RDDivide;
    private javax.swing.JRadioButton RDMinus;
    private javax.swing.JRadioButton RDSum;
    private javax.swing.JRadioButton RDTime;
    private javax.swing.JTextField SoA;
    private javax.swing.JTextField SoB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtDivide;
    private javax.swing.JTextField txtMinus;
    private javax.swing.JTextField txtSum;
    private javax.swing.JTextField txtTime;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
